### ISSUE TITLE
Latest version of `extract_doc` breaks feature "Table of Conent"

### ISSUE THREAD

**Issue by duhoobo** [Pelican-Elegant/elegant#154]
If I,

Use [TOC] in markdown files, and
add "toc" in MD_EXTENSIONS and enable extract_toc at the same time,
then no toc in my final html, article.toc is empty too.

After some debugging, I find that PandocReader overides default MarkdownReader due to its high prioritiy when dealing with files with ".md" suffix. And it seems PandocReader isn't able to handle [TOC] somehow. I'm not sure about this.

**Comment by talha131** [comment]
@duhoobo Have you tried [this guideline](https://github.com/getpelican/pelican-plugins/tree/master/extract_toc#pandoc-reader)?

I suggest you open this issue at [Pelican Plugins repository](https://github.com/getpelican/pelican-plugins/issues). I see an [issue already open](https://github.com/getpelican/pelican-plugins/issues/582) that pertains to PandocReader. Is it related to your issue?

**Comment by ShaunaGordon** [comment]
I've also noticed that something has changed in recent months and broken the [TOC] behavior. I'm not sure exactly what changed (though, since Github shows extract_toc hasn't changed for something like 2 years, I assume the answer lies in a change made to PandocReader), but it does appear to stem from how extract_toc deals with/checks for Pandoc.

This is illustrated in my own blog:

[Wayback Machine has some of my blog posts as recently as the end of March, which show the TOC working](https://web.archive.org/web/20160325182818/http://shaunagordon.com/blog/2016/01/13/pelican-travis-and-github/)

However, the latest builds with the current official extract_toc show it not working: ![toc not working](https://cloud.githubusercontent.com/assets/579361/16463239/e8ec6d94-3e02-11e6-8f87-06248b5000e5.png)
)

Unfortunately Wayback Machine only goes as recently as the end of March for my site for some reason, so I can't better pinpoint when it broke. I did find, upon looking at my commit history, that in the beginning of May, I had to tell TravisCI to install Pandoc, where I did not have to, previously. I had run into a situation where none of my content would be published, and the build log had a rash of "could not process, no such file or directory" errors, though the build would still pass. You can see the errant behavior in [this build](https://travis-ci.org/ShaunaGordon/shaunagordon.github.com/builds/141145818), while installing pandoc from the OS's repository [fixes this issue](https://travis-ci.org/ShaunaGordon/shaunagordon.github.com/builds/141146719), but then the [TOC] command is ignored entirely and we're left with the literal text in the output.

In looking through the issue you linked, I found [this pull request](https://github.com/getpelican/pelican-plugins/pull/729) that modifies extract_toc to make its checking for Pandoc more robust and not activate Pandoc/PandocReader when it's found in the plugins folder, but not actually activated in the Pelican config. I've tossed it into my build sequence and, [as you can see on the live site](http://shaunagordon.com/blog/2016/01/13/pelican-travis-and-github/) [TOC] works again.

So, that leaves sufferers of this issue two options:

1. (The one recommended in the comments of the above-linked issue.) Remove PandocReader from your plugins directory.
1. Use the patched extract_toc.py file in that pull request.

Which is the "right" one probably depends on the specifics of one's install. Hopefully this helps the others affected by this.

**Comment by talha131** [comment]
Thank you @AWegnerGitHub

**Comment by talha131** [comment]
@all-contributors please add @duhoobo and @ShaunaGordon  for bug.

**Comment by talha131** [comment]
@all-contributors please add @ShaunaGordon for bug.

**Comment by talha131** [comment]
@all-contributors please add @AWegnerGitHub for code, doc, bug, maintenance
