### ISSUE TITLE
Favicon not recognized

### ISSUE THREAD

**Issue by scottfurry** [Pelican-Elegant/elegant#159]
I had followed the instructions [here](http://oncrashreboot.com/elegant-best-pelican-theme-features#favicon-and-speed-dial-icon), but the favicon would not be presented in FF browser.

A search in theme template files for "favicon" found a reference in `elegant/templates/_includes/_defaults.html` to a variable not disclosed in the [theme configuration variables](http://oncrashreboot.com/elegant-best-pelican-theme-features#configuration-variables) as being necessary.

Setting variable `USE_SHORTCUT_ICONS` in the `pelicanconf.py` enabled favicon presentation.

**Comment by jihenghu** [comment]
1.  in 'pelicanconf.py' , set    
 `USE_SHORTCUT_ICONS = True`    
`SITELOGO = 'images/favicon.ico' `  
`FAVICON = 'images/favicon.ico' `  
`SITELOGO_SIZE = 15 `   
2. put your `favicon.ico` in path `content/images/` ;
3.  in  `elegant/templates/_includes/favicon_links.html`   
 replace following ：
 `<link rel="shortcut icon" href="{{ SITEURL }}/theme/images/favicon.ico" type="image/x-icon" type="image/png" />`  
with  
`<link rel="shortcut icon" href="{{ SITEURL }}/images/favicon.ico" type="image/x-icon" type="image/png" />`  
since your favicon will be copied into path `output/images/` instead of `output/theme/images/`

**Comment by silverhook** [comment]
@scottfurry, does the above instruction fix it for you?

What about if you update Elegant to the newest version?

If not, we will close this issue.

**Comment by scottfurry** [comment]
Reviewing my code, I discovered I'm not using the elegant theme anymore.
Best if we close for now.

**Comment by silverhook** [comment]
@scottfurry, thanks for your quick reply.

BTW, we have recently rekindled the activity on Elegant, so if you are still interested in this theme, a 2.0 version is imminent and the future is bright. (see #173 and #192 for details)
