### ISSUE TITLE
Change RELEASE_NOTES.md to ChangeLog

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#241]
As discussed in https://github.com/Pelican-Elegant/documentation/issues/52, we should change https://github.com/Pelican-Elegant/elegant/blob/master/RELEASE_NOTES.md to change it into a traditional `ChangeLog` – [see Wikipedia article for naming and format convention][wp] – and make it a rule that when a new feature or (big) bug is fixed, it should be documented there as well in the same PR.

Then we could simply include the changelog into the release notes, when we write them.

[wp]: https://en.wikipedia.org/wiki/Changelog

**Comment by iranzo** [comment]
if we use release tagging, 'pbr' module helps into writing it <https://pypi.org/project/pbr/>

**Comment by silverhook** [comment]
PBR looks quite useful, yes.

**Comment by iranzo** [comment]
Changelog as generated by PBR: https://paste.fedoraproject.org/paste/LCZsJsRBYrVUYj26VPvjeQ

Authors as generated by PBR: https://paste.fedoraproject.org/paste/RG4DANKmSmLg2jPDDePBHQ

If you like it, I can submit PR for adding setup.py and setup.txt so that Changelog and Authors will be created with python setup.py sdist (and then git add and commit)

**Comment by iranzo** [comment]
As I already did it for the test, here it is the PR: https://github.com/Pelican-Elegant/elegant/pull/242

**Comment by silverhook** [comment]
`ChangeLog` and `AUTHORS` look good to me, yes.

This would also be a good MVP for #227, and we can change that issue to _extend_ the contribution list.

Thanks for implementing this :)

**Comment by iranzo** [comment]
Do we want for 'once' to rewrite master logs by squashing comments and force overwrite of the branch to rewrite full history and have a working change log after it?

**Comment by iranzo** [comment]
Draft for release notes done from mobile

Please do ammend it

Regards
Pablo

Sent from mobile

El 29 dic. 2018 19:24, "Talha Mansoor" <notifications@github.com> escribió:

@iranzo <https://github.com/iranzo> and @silverhook
<https://github.com/silverhook> for change log, we must make sure to remove
fluff commits. This won't be necessary if we make sure every PR has
squashed commits.

Secondly, we may still need to review and edit the change log. To clarify
the language and categorize change log into sections (New, Bug fixes,
Breaking changes etc).

But it is a great addition. Thank you @iranzo <https://github.com/iranzo>.
Our 2.0 release is ready. We are mainly blocked by the announcement article
in documentation. Your contribution will enable us to write release note
quickly.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Pelican-Elegant/elegant/issues/241#issuecomment-450511088>,
or mute the thread

**Comment by iranzo** [comment]
Draft for release notes made on the mobile...
[elegant2 (1).txt](https://github.com/Pelican-Elegant/elegant/files/2719540/elegant2.1.txt)

**Comment by talha131** [comment]
> Do we want for 'once' to rewrite master logs by squashing comments and force overwrite of the branch to rewrite full history and have a working change log after it?

Oh please. No. Never. Upstream should never be rebased. Bad things will happen if change the upstream.

But for future, we must make sure commit messages are succinct and explanatory. As for squashing, I have been doing it using Github or from cmd. We do ask contributor to squash the commits in the [Contributing doc](https://github.com/Pelican-Elegant/elegant/blob/master/CONTRIBUTING.md)

**Comment by iranzo** [comment]
Document put in https://github.com/Pelican-Elegant/documentation/pull/56

**Comment by silverhook** [comment]
@iranzo, I gave some feedback in your PR and will also make my draft available (sorry that I didn’t push it sooner and had it lying on the disk), so we can merge the two.

I’m reopening this issue as the ChangeLog is still of non-standard format.

**Comment by iranzo** [comment]
I fixed my PR with your feedback (missing to get the new file in your PR regarding community development).

About the changelog, pbr (python setup.py sdist) will generate a ChangeLog that can be used as base to review a markdown one (it will require to use 'tags' for releases to automatically build it)

**Comment by silverhook** [comment]
IMHO we can certainly try. If it doesn’t work as well, we can always change it later.

**Comment by iranzo** [comment]
Let me ellaborate a bit more: pbr does create the ChangeLog file, but for the markdown, someone will still need to redact and create based on 'something', if we want to use the MD version, it's probably better, but will require still some 'look-back' to find out what was fixed before a release, and pbr can automate that part.

**Comment by silverhook** [comment]
Sure. That sounds like a sensible approach. We can have the auto-generated raw changelog (e.g. CommitLog.txt) and a proper `ChangeLog.md` that we create out of that …or something in those lines.

**Comment by silverhook** [comment]
I think we can simply remove this issue from the 2.0 milestone. As it’s about an improved format of the ChangeLog, it shouldn’t be a blocker for 2.0.

It’s good enough for 2.0 and the rest we can do later.

**Comment by iranzo** [comment]
+1

**Comment by talha131** [comment]
@silverhook can you please share which format for changelog you want to conform to?

@iranzo how do I run pbr for author and changes locally?

**Comment by iranzo** [comment]
@talha131 'python setup.py sdist'

it will generate the ChangeLog, Authors, etc

**Comment by talha131** [comment]
We have added automatic changelog creation on new releases.

**Comment by silverhook** [comment]
Looks great, thanks for setting this up. And I apologise for not replying sooner. Was busy :/

**Comment by talha131** [comment]
> And I apologise for not replying sooner. Was busy

No issues. Good to have you back.
