### ISSUE TITLE
the archives, tags and categories didn't display on a nginx server

### ISSUE THREAD

**Issue by josephzjw** [Pelican-Elegant/elegant#276]
When I use `pelican -l` in the localhost everything is okay, but when I publish the output to the nginx server it shows 404 not found error. Other pages are correct. I found that all the archives, tags and categories are **directories** in the output file. Their names are **archive**, **tag** and **category**. Is it mismatched with the name that cause the problem? 

When I switch to another theme with tag and archive available, everything is okay... So I guess the problem is not my configuration of nginx server...

**Comment by talha131** [comment]
@josephzjw You will have to provide source code of your blog along with the configuration file so that we can test and try to reproduce the issue at our end.

But first, we had a similar issue sometime ago. Please go through it and see if it helps.

https://github.com/Pelican-Elegant/elegant/issues/250

**Comment by josephzjw** [comment]
It works when I followed the instructions you provided #250  Thanks!
By the way, why at localhost I don't need to specify the archives, tags and categories url and they still work correctly....

**Comment by talha131** [comment]
> I followed the instructions you provided

@josephzjw  hmm, can you please write here what worked for you. We may need to add it to documentation.

**Comment by josephzjw** [comment]
I followed the solution of azzamsa, add the three line codes below at the pelicanconf.py
```
TAGS_URL = 'tags.html'
CATEGORIES_URL = 'categories.html'
ARCHIVES_URL = 'archives.html'
```
Then I use `pelican` to generate the website and type `service nginx reload` to reload the nginx service. Finally it works...

**Comment by talha131** [comment]
Thank you @josephzjw We will look into it in detail. According to my understanding Elegant should have worked out of the box. We will either fix our code or update our documentation.

**Comment by alxpettit** [comment]
I can confirm this issue. The reason it happens is because the nav bar is rendered with links pointing to e.g. `site.com/archives` instead of `site.com/archives.html` -- I'm not sure if other servers automatically add a .html for blank queries, but nginx does not do this -- and it results in a `404`.

**Comment by andrewdstrain** [comment]
This issue doesn't affect just Nginx and the "fix", above, shouldn't be needed because the templates give the wrong default values.

Try `twistd -on web --path=output` on any Pelican website with the Elegant theme (from master branch) and the URLs generated will fail.

![twistd example](https://user-images.githubusercontent.com/29258172/61694507-9c464680-acff-11e9-8fdf-84f0b7fd4427.png)

If you look at the source code, you see code like this:

```
<a class="category-link" href="{{ SITEURL }}/{{ CATEGORIES_URL|default('categories') }}#{{ category.slug }}-ref">{{ article.category }}</a>
```

The problem is in the `default('categories')` part of the code. Pelican, by default, generates 'categories.html', not 'categories'. When using the `pelican -l` command as a web server, wrong default works because the web server adds `.html` to the URL that isn't found. That is, you can have both `http://lcoalhost:8000/index` and `http://localhost:800/index.html` and the Pelican web server will pull up the same file. Other web servers, like Nginx, `twistd -on web --path=output`, Apache, etc., doesn't do that by default and can not find `http://lcoalhost:8000/index` at all.

This Diff is how I fixed the problem in the template code of the Elegant theme.

[elegant.diff.txt](https://github.com/Pelican-Elegant/elegant/files/3420924/elegant.diff.txt)

**Comment by talha131** [comment]
Thank you @andrewdstrain. I will look into it in detail and get back to you.

**Comment by talha131** [comment]
I have fixed this issue in here

https://github.com/Pelican-Elegant/elegant/pull/480

It's available on the next branch. It will release to master in couple of days.

@andrewdstrain I am specially thankful to you for explaining the issue in detail. If you greatly appreciate if you can manage sometime to review my fix. This is the commit which fixes the issue https://github.com/Pelican-Elegant/elegant/pull/480/commits/3c7df6ad37dbc44ed34b11ff8036242d52874fbd

**Comment by talha131** [comment]
@all-contributors please add @josephzjw for bug
