### ISSUE TITLE
Add support for Disqus alternative

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#288]
Pick an open source, privacy conscious, free and easy to host (like using Github or Gitlab) alternative.

For example,

1. https://github.com/gitalk/gitalk
1. https://github.com/imsun/gitment
1. https://vssue.js.org/
1. https://github.com/eduardoboucas/staticman

We will pick one, that is most active and has best support.

We will also move documentation site to that solution.

Activity on these alternates clearly indicate Disqus is not the only game in town for static sites anymore. We should switch.

**Comment by azzamsa** [comment]
I will be very glad to have disqus open source alternative

**Comment by azzamsa** [comment]
Sure they are a lot of Disqus alternative witch explained nicely [here](https://darekkay.com/blog/static-site-comments/). Categorized into: Integrated third-party, Off-site hosting, Self-hosted, and GitHub/Gitlab.

I think we are here focusing on Github/Gitlab categories:

- https://github.com/utterance/utterances ; 808 :star: ; [Github only](https://github.com/utterance/utterances/issues/96)
- https://github.com/imsun/gitment : 3,428 :star: ; [Github only](https://github.com/imsun/gitment/issues/177)
- https://github.com/eduardoboucas/staticman : 1,337 :star: ; [Github/Gitlab](https://github.com/eduardoboucas/staticman/pull/219)

this is [hugo + staticman](https://networkhobo.com/2017/12/30/hugo-staticman-nested-replies-and-e-mail-notifications/), and [jekyll + staticman](https://mademistakes.com/articles/improving-jekyll-static-comments/). Would be awesome if we had [Elegant + staticman].

I like staticman more because we able to use Gitlab issue, if something bad happen, we still have those comments in our hand. cause Gitlab is open.

**Comment by talha131** [comment]
Note to self:

1. https://victorzhou.com/blog/replacing-disqus/
1. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/

In docs, highlight the fact that elegant loads Disqus only when comments accordion is clicked.

**Comment by VincentTam** [comment]
> I like staticman more because we able to use Gitlab _issue_, if something bad happen, we still have those comments in our hand. cause Gitlab is open.

@azzamsa Hi, this is the maintainer of @staticmanlab, a public GitLab instance of Staicman.  Staticman makes use of GitHub/GitLab Pull/Merge Requests instead of issues.  Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under `data/comments`, configurable through the `path` parameter in _root-level_ `staticman.yml`), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content.  This gives a total ownership of a static site's comments.

IMHO, comments are part of the site's content, not a problem of a software package.  To illustrate this, let me use an [MR for a static comment](https://framagit.org/staticman-gitlab-pages/bhdemo/merge_requests/5) received on [my Framagit+Beautiful Hugo+Staticman demo site](https://staticman-gitlab-pages.frama.io/bhdemo/).

| Field       | Content                                                                                     |
| ----------- | ------------------------------------------------------------------------------------------- |
| replyThread |                                                                                             |
| replyID     |                                                                                             |
| replyName   |                                                                                             |
| comment     | Essai : $n!\underset{+\infty}{\sim}\left(\frac{n}{e}\right)^n\sqrt{2\pi n}$.
Ok ? :smiley: |
| name        | François Coulombeau                                                                         |
| email       | 137743b032171d66c4caa2be6b0884c3                                                            |
| website     |                                                                                             |
| date        | 2019-02-28T22:44:08.269Z                                                                    |

This is rendered as  
[![screenshot for rendered comment](http://imgur.com/KRTtJLXl.png)](https://staticman-gitlab-pages.frama.io/bhdemo/posts/my-second-post/)  
Image URL: http://imgur.com/KRTtJLXl.png  
in my page.

* * *

@talha131 Among the three alternatives to Disqus that @azzamsa has suggested, only Staticman _doesn't_ load external JavaScripts for comment retrieval.  The other two come with scripts.  I've not tried to install them, so I can't tell the impact on the load speed.  However, as the screenshot shoes, Staticman allows writing in Markdown (or even in LaTeX if you want), and _doesn't_ require the commenter to login to GitHub/GitLab.  That would greatly facilitate the commenting process.

**Comment by silverhook** [comment]
I have heard really good stuff about <https://posativ.org/isso/> and the last time I looked for a lightweight self-hosted comment system, that seemed the best option to me.

The [repo](https://github.com/posativ/isso) seems to be still actively maintained as well.

**Comment by iranzo** [comment]
They present themselves as drop-in replacement for disqus, so probably a nice try to just 'add-it' by copying what's there for disqus

**Comment by silverhook** [comment]
This may be relevant then: https://github.com/getpelican/pelican-plugins/issues/341

**Comment by iranzo** [comment]
I was checking and it seems to require you to host the server (that stores in sqlite), so really not a replacement for disqus that is provided by 3rd party but still can be integrated and whoever wants it, can just use by setting fewer things on Elegant

**Comment by talha131** [comment]
Exactly what @iranzo has pointed out. isso is great but it requires user to self host it. Other options like staticman does not require setting up a host. All they need is configuring a github or gitlab repository which is far easier than setting and maintaining a host.

Nonetheless adding support for isso should not a big problem though we won't be able to test it. I say we put off isso support until some user steps up who has an isso instance running.

**Comment by VincentTam** [comment]
I've tested Isso to see verify its claim about Markdown syntax support.  Unluckily, images _aren't_ rendered on the demo site.

![sample isso comment](http://i.imgur.com/eilGa8xl.png)
Image: [my sample Isso comment](http://i.imgur.com/eilGa8xl.png)

Source of the test comment:
```
How about blockquotes and pictures?

> Sample quote

Sample picture?
![sample picture](https://staticman-gitlab-pages.frama.io/huginn/img/avatar.png)
```

Expected results:

>How about blockquotes and pictures?
>
>> Sample quote
>
> Sample picture?
> ![sample picture](https://staticman-gitlab-pages.frama.io/huginn/img/avatar.png)

---

The bottom part of [Isso's overview](https://posativ.org/isso/docs/) contains some more links to open-source commenting services, so Isso isn't the only alternative.

> They present themselves as drop-in replacement for disqus, so probably a nice try to just 'add-it' by copying what's there for disqus

@iranzo @silverhook I really like it's edit functionality, apart from being lightweight.  That might help eliminate typos and enhance user experience.  I would like to draw your attention to [some SEO issues about Isso](https://github.com/posativ/isso/issues?utf8=%E2%9C%93&q=seo) before drawing the conclusion.

I've tried simulating [how a search bot view the demo page](http://www.browseo.net/?url=https%3A%2F%2Fposativ.org%2Fisso%2F).  As espected, the Isso comments _aren't_ displayed in the simulated results. Perhaps that's what the bot actually sees.

```
   <script data-isso="//posativ.org/isso/api/"
            src="//posativ.org/isso/api/js/embed.min.js"></script>
...
    <div class="demo">
        <h2>Demo</h2>
        <section id="isso-thread"></section>
    </div>
```

IMO, useful comments are usally static contents (at least, after the allowed period of 15 minutes) of the site and they should be treated as part of the page contents.

* * *

> Exactly what @iranzo has pointed out. isso is great but it requires user to self host it. Other options like staticman does not require setting up a host.

@talha131 You're right that using Staticman doesn't require setting up a host as longs you're using the one setup by someone else.  I've set up mine for testing Staticman PR 219.<sup>1</sup>  That might be sufficient for small and personal sites.  For bigger ones, a custom API instance might suit your needs better because unnotified updates won't break things (c.f. eduardoboucas/staticman#283).

---

Please note the convenience-customisability tradeoff: simple code comes with a bunch of pre-defined config.  To tailor it to your needs, one has to go deep into the settings.  For instance, Isso _don't_ support Markdown preview.  Nonetheless, although (and because) a [Staticman's minimal example](https://gitlab.com/ntsim/test-staticman) can be so basic that you may add any features you like, like

1. [adding scores :star: to HTML forms](https://donboulton.com/2018-02-26-post-staticman-with-gitlab)
2. [enable Markdown preview](https://zcrc.me/retromini/2019/05/17/opendingux-release-20190517.html)
3. enable reCaptcha support (see the second example, not suuported in posativ/isso#201)

- - -

1. I've set deployed one for [GitLab.com](https://staticman3.herokuapp.com) and one for [Framagit](https://staticman-frama.herokuapp.com) since it's [API config](https://staticman.net/docs/api#githubToken) parameter `gitlabBaseUrl` supports at most one GitLab instance.

**Comment by talha131** [comment]
One more alternative is Netlify comments

1. https://github.com/netlify/gotell
1. https://github.com/netlify/netlify-comments-starter

It needs to be confrimed if using it blocks user in the Netlify eco system or not.

**Comment by talha131** [comment]
Staticman feature of anonymous posting is very useful. But I just tried the [demo](http://popcorn.staticman.net/) and it's not working.

![](https://i.imgur.com/vebh6Q4.png)

I also tried @VincentTam website. When I posted a comment, it took me to this page

![](https://i.imgur.com/Lke1T0p.png)

which is not very user friendly.

Lets not give up on staticman for a while and see if the issue gets fixed. 

---

I don't like gitment for [this reason](https://github.com/imsun/gitment#4-initialize-your-comments)

> After the page is published, you should visit your page, login with your GitHub account(make sure you're repo's owner), and click the initialize button, to create a related issue in your repo. After that, others can leave their comments.

---

Other options require Github account to comment. Of all of them utterances seems the easiest.

---

Summary, so far,

1. I like staticman but we can't use it if it is unmaintained
1. We should avoid Github account restriction if possible
1. I am yet to review Netlify comments
1. After staticmen, my second preferrance is utterances

**Comment by VincentTam** [comment]
> Staticman feature of anonymous posting is very useful. But I just tried the [demo](http://popcorn.staticman.net/) and it's not working.
> 
> ![](https://camo.githubusercontent.com/46bcb0bb6a429a0e1d5d7a31a008fb9ffda56139/68747470733a2f2f692e696d6775722e636f6d2f766562683651342e706e67)
> 
> I also tried @VincentTam website. When I posted a comment, it took me to this page
> 
> ![](https://camo.githubusercontent.com/97a632b0ab727b26432953ed02046312ae58bb49/68747470733a2f2f692e696d6775722e636f6d2f4c6b65315430702e706e67)
> 
> which is not very user friendly.
> 
> Lets not give up on staticman for a while and see if the issue gets fixed.

@talha131 Which browser/OS are you using?  I couldn't reproduce that error with Firefox on Ubuntu 18.04 LTS.

![Screenshot from 2019-06-25 15-10-50](https://user-images.githubusercontent.com/5748535/60101140-80c93980-975b-11e9-9437-8c7bfee2d6a8.png)

**Comment by talha131** [comment]
@VincentTam thanks for the prompt response. I am using Firefox dev editon 68.0b11 (64-bit) on 10.14.6 Beta. 

Let me try your site on Chrome.

**Comment by talha131** [comment]
Your site works on Chrome. Probably some Firefox setting or addon is interfering causing the issue.

Though Staticman demo does not work even in Chrome.

**Comment by VincentTam** [comment]
> @VincentTam thanks for the prompt response. I am using Firefox dev editon 68.0b11 (64-bit) on 10.14.6 Beta.

You're welcome, though I can't help much on technical stuff like browser/OS-specific issues.

> I missed to note that staticman needs a server instance to run its app, something we can't expect from users.

Staticman does require an API instance, but it can be a third-party one instead of your own.  As a result, many users have chosen the official production/development API instances for convenience.  Nonetheless, some users have reported unexpected error in https://github.com/eduardoboucas/staticman/pull/285 due to unnotified updates in the official API instances.  To reassure stable static comment service, I suggest using an alternative API instance.

:information_source: As my user bio reads, I've built @staticmanlab.

> Though Staticman demo does not work even in Chrome.

The official Popcorn demo is using Staticman v2, which will be obsolete due to v3.  As I don't know Node.JS and GitHub Apps, I'm not interested in finding out the actual cause.  Staticman v3's change from a GitHub bot user to a GitHub App might cause such error, but who knows?

**Comment by OrKoN** [comment]
I develop a comment system called [JustComments](https://just-comments.com). There is a hosted version starting from $5 per month or one can also self-host it using https://github.com/JustComments/jc-server and https://github.com/JustComments/jc-widget (feature set is a bit limited although one could extend it)

@talha131 told me that JustComments was considered but I actually don't see a link to it so take a look pls.

**Comment by azzamsa** [comment]
Oh, now we decide to use utterances, according to this commit: https://github.com/Pelican-Elegant/elegant/commit/a2151cc25c5a49b7ef6dd7f86e7ebc5bac03465f

The reason based on @talha131 comment https://github.com/Pelican-Elegant/elegant/issues/288#issuecomment-505424976

- we love staticman, but it's unmaintained.
- our second preference is utterances, the cons of this is we have to have Github account (even though we want to avoid Github restriction). We choose this way (utterances) because it's the easiest for end user and still maintained.

Is my summary true @talha131 ?

**Comment by talha131** [comment]
@azzamsa I chose utterances because

1. At the time of dev, the staticman demo was not working. It was clear it is not being maintained or their bot is under heavy load.
1. Utterances demo page worked well.
1. It was a breeze to set up and integrate.
1. It has theme support. Something we can tweak in the future.
1. Finally, [Philipp Oppermann's blog](https://os.phil-opp.com/paging-implementation/) uses it.

It does not mean Utterances is the last comment system to be added to Elegant. We are open to PR for other comment system.

My personal preference is these options.

1. https://just-comments.com/
1. https://github.com/umputun/remark
1. https://www.talkyard.io/

I didn't pick these options for this issue because they require a server to set up or pay for service. 
Although they are much better than Utterances. I may add support for these in the future. Others are welcome to open PR.

**Comment by azzamsa** [comment]
Hi. thanks for that. Yeah for now I think the simplest one is utterances. Besides it use proprietary github issue. We have no other choices for now except self-hosting (which can be daunting task for end-user).

Btw. Why I don't find `UTTERANCES_REPO` value in both of this config https://github.com/Pelican-Elegant/elegant/blob/master/documentation/pelicanconf.py, and https://github.com/talha131/onCrashReboot/blob/master/pelicanconf.py ? Is this intended? so the default value is the repo it hosted?

**Comment by talha131** [comment]
> We have no other choices for now except self-hosting (which can be daunting task for end-user).

Yeah, that's the issue. Right now, I am not sure if our users are willing and able to host their own servers or to put out money for hosted solutions like just-comments or TalkYard.

I am waiting for users to come up.

**Comment by azzamsa** [comment]
That's what I'm thinking too. Let's say we bought smallest droplets, it's 5$/month just in order to self host isso. I think my blog don't need that for now. It's not worth for blog that didn't have that huge visitors.

**Comment by talha131** [comment]
>  I think my blog don't need that for now. It's not worth for blog that didn't have that huge visitors.

Have a look at TalkYard pricing. Or use [Amazon Lightsail](https://aws.amazon.com/lightsail/) to host Remark. Remark does not require separate DB. It's less than $5, though personally I cannot justify it too for my blog which I haven't got in the habit of regularly updating yet.

**Comment by VincentTam** [comment]
> 1. At the time of dev, the staticman demo was not working. It was clear it is not being maintained or their bot is under heavy load.

@talha131 There're an array of working Staticman v3 demo**s** on Framagit.

Let me repeat again, the official popcorn demo doesn't work since the HTML form action URL hasn't been updated with Staticman v3 API scheme introduced in Staticman PR 219 AND the bot @staticmanapp is unavailable, as reported in eduardoboucas/staticman#306.  The demo is not maintained doesn't mean that the node.js app doesn't work.  Other Staticman bots like @staticmanaima, @Bloggerbust-bot function well.
