### ISSUE TITLE
Document disable comments

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#303]
Document https://github.com/Pelican-Elegant/elegant/pull/269 setup and usage

**Comment by talha131** [comment]
@azzamsa any update on this.

**Comment by azzamsa** [comment]
I have final exam that will end in this month, I'll be ready in the next month, but if you in hurry I don't mind if you take over this.

**Comment by talha131** [comment]
> I don't mind if you take over this.

Nah. It's ok. We will wait.

**Comment by talha131** [comment]
We have it here https://elegant.oncrashreboot.com/disable-comments-per-article

**Comment by azzamsa** [comment]
Great, I will add other missing docs.

**Comment by talha131** [comment]
> Great, I will add other missing docs.

@azzamsa You are more than welcome to add docs. But I would suggest you to focus on code related issues instead of docs for a while.

It's because now we have around 70 articles in our documentation which is pretty good. Moreover, @jackdewinter has expressed willingness to contribute to the documentation via email and has shown promising progress.

So instead of docs, if you can fix issues and add features that would be a better use of your technical skills for you have contributed some interesting features in the past.

I do **not** mean to say documentation is not important or that no one except Jack should work on it. No, that's not my intention. 

As of now, most of the issues open are easy to fix but they require time investment, where we can really use your help. For example, 

1. https://github.com/Pelican-Elegant/elegant/issues/237
1. https://github.com/Pelican-Elegant/elegant/issues/140
1. https://github.com/Pelican-Elegant/elegant/issues/251
1. https://github.com/Pelican-Elegant/elegant/issues/385
1. #300 

In the end, you are free to contribute to whichever issue you life.

**Comment by talha131** [comment]
@all-contributors please add @azzamsa for code, docs

**Comment by azzamsa** [comment]
@talha131 Great, thanks for suggestion. I'll focus on code related issue then :)
