### ISSUE TITLE
Do we want to setup analytics?

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#329]
I was thinking that as we do have the site claimed on google (to submit sitemap, etc) it would be also 'easy' to push a tracker so that we can get website statistics.

So... room open for discussion here...

**Comment by talha131** [comment]
We should have collected some sort of analytics. Why? Because right now, I have no idea level of public interest in this project.

We are blind. How many people are using Elegant? No idea. What kind of people use it? No idea. Do users visit the doc site? No idea.

Should have listed to @iranzo then 😆 

----

- [ ] is it possible to open Google Analyitcs result to public
- [ ] is it possible to open Google Analyitcs result to team members
- [ ] Light weight GA alternative
    * [ ]  https://minimalanalytics.com/
    * [ ]  https://github.com/jehna/ga-lite
- [ ] Any other alternative?

**Comment by iranzo** [comment]
For google analytics we can share 'access' to others 'one by one' not sure if for public access

Regards,
Pablo
