### ISSUE TITLE
GDPR autotemplate?

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#479]
## Mandatory Step

- [x] I am using latest production release of Elegant

## Recommended Step

- [ ] I have attached link to my blog source code repository, so that developers can try to reproduce the issue at the end
- [ ] I can't my source code but I have linked my pelican configuration files to help developers reproduce the issue

## Description

**Describe the bug**
Currently we do have some 'banners' when using monetization, etc

As we do enable integration with Google Analytics, Amazon Referrals, and others, would it make sense to auto 'render' a static page with all the warnings for the products used similar to the GDPR definition that many websites host?

**Comment by talha131** [comment]
Google analytics and other analytics does not require public disclaimer.

We added disclaimer for Amazon because it was required in their terms and conditions.

For now, it would be over kill to add a separate disclaimer page or "this website use cookies" like warning that we come across on so many European sites.

**Comment by iranzo** [comment]
Exactly, but theoretically many sites define that uses services from 3rd party like Disquss, GA and point to their respective GDPR pages

(seen on other european pages)

**Comment by talha131** [comment]
What can we do as a theme? 

1. Say we add a page, then user will have to add the page in the `DIRECT_TEMPLATES`.
1. We will add passages for all the services to the page like "This site uses Google Analyitcs". "This site uses Amazon..."
1. Each passage has to be enclosed in the conditional block. Like if GA is defined then show passage for Google analytics

After all this, how will user link to this disclaimer page?

I see where you are coming from. As a theme there isn't much we can do. 

If we add a page then user still will have to do lot of manual work to utilize it. Like defining Direct_templates or linking to the generated page.

And we will have one more thing to maintain on our hand. The value we get from the effort involved in very little.

---

Let me know how you will approach this problem? What's the end result you have in mind? A banner or a page? How will user enable the banner or link to page? What will be the content of the banner or page?

It appears you have some example in mind that I am not aware of.

**Comment by iranzo** [comment]
What I had in my mind is similar to what you described, page with conditional blocks adding text when features are used and ability to list that page on the footer in a similar way to what is done with Amazon monetization.

Still if doesn't seem easy or straighforward we can just skip it

**Comment by talha131** [comment]
> ability to list that page on the footer in a similar way to what is done with Amazon monetization.

In case of amazon, we just show a disclaimer. We can't use similar style for all the disclaimers because they all won't fit in the footer.

Our available options are,

**First**

 Redesign footer so that it can accomodate more disclaimers. 

Problem with this approach is some disclaimers are for one time only. Surely  you don't want to keep telling user that he is being tracked via GA. No one does it.

Nonethless, this approach can work.

**Second**

Show pop ups like we see for cookies. 

Bad idea. No one likes pop ups.

**Third**

1. Add a template page like I have described above
1. Tell user to add it in Direct templates
1. Link to the page in footer 

This seems like a good option.

----

> Still if doesn't seem easy or straighforward we can just skip it

Well, everything is straight forward, once you have figured it out.

If you want to implement it then sure go ahead. Personally, I don't see much value in it. But my opinion does not matter in this case. It's possible your site visitors are privacy minded and would like to read such disclaimer. 

Let me know what you think. If you want to implement it then please reopen this issue.
