### ISSUE TITLE
[Help] TOC Size

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#509]
Is the TOC designed to be that small ?

![image](https://user-images.githubusercontent.com/17734314/65810228-fc5eda80-e1d1-11e9-83dd-06163d9c6a14.png)

**Comment by talha131** [comment]
It can be improved for sure, as long as it stays out of the way.

It is so small because we use the Bootstrap grid. On smaller screens, the grid gets too small to fit TOC, in which case TOC looks ugly.

I opted for a quick and dirty solution, i.e. reduce the font size.

What's better?

1. Use CSS grid and make layout flexible
1. If grid is small to fit the TOC then hide it and show it only when user clicks a button.

**Comment by azzamsa** [comment]
> What's better?
> 
>     1. Use CSS grid and make layout flexible
> 
>     2. If grid is small to fit the TOC then hide it and show it only when user clicks a button.

Giving recommendation is easy, But I can't say anything for now, since I'm unable to give that PR my self. :)

**Comment by talha131** [comment]
I have added it to 2019-Q4. It is dependent on #429
