### ISSUE TITLE
[Request] Add favourite article

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#531]
## Goals

If we had hundreds of article, it's better to inform reader which one to read first.

Inspiration: [Julia Evans's blog](https://jvns.ca/)

## working code

``` diff
Unstaged changes (1)
modified   templates/archives.html
@@ -57,8 +57,13 @@ Full archives of {{ SITENAME|striptags|e }} blog.
                     {% endif %}
                 {% endif %}
 
-                <a href="{{ SITEURL }}/{{ article.url }}">
-                    {{ article.title }}
+               <a href="{{ SITEURL }}/{{ article.url }}">
+               {% if article.favourite %}
+                    {{ FAVOURITE_SYMBOL }} {{ article.title }}
+                    {% else %}
+                      {{ article.title }}
+                    {% endif %}
+
                     {%if article.subtitle %}
                     <small class="subtitle">
                         {{ article.subtitle }}
```

![image](https://user-images.githubusercontent.com/17734314/68986682-5edc6a80-0854-11ea-8303-0b3c467a4e57.png)

in `pelican.conf`:

```
FAVOURITE_SYMBOL = "🌟"
```

**Comment by azzamsa** [comment]
oh, no. that bug label added automatically after I choose 'bug' template. even if I remove the [bug] tag :)

**Comment by azzamsa** [comment]
@talha131 if pelican teams okay with this. I will make appropriate PR.

**Comment by talha131** [comment]
@azzamsa couple of feedback.

# Do we really need it?

I have seen some blogs create a special page, "Start here", or "Essential Readings" or "Greatest Hits". They list their essential and popular articles in it.

For example: 

1. https://www.kalzumeus.com/greatest-hits/
1. https://www.kalzumeus.com/start-here-if-youre-new/

Users can do similar in the Elegant theme. Pages appear in the top menu bar automatically.

## If you insist

I have no strong feelings on this feature. You are more than welcome to open PR provided you take care of following things.

1. The symbol should be a Unicode emoji instead of SVG or PNG image
1. Symbol should be configurable like ⭐️ or 🥇 or 🔖 or 📌 or 📍 (I see you already have that 👍 )
1. Symbol should appear in the list on Categories, tags and archives pages

### Questions?

1.  How to show this information on the article page? If in the sidebar then under what heading?
1. Should be make it configurable such that the user can rate his article like some articles are five stars (⭐️⭐️⭐️⭐️⭐️) and some only 2 (⭐️⭐️)?
1. Should we have a new page to automatically generate a list of favorite articles?

**Comment by azzamsa** [comment]
> Do we really need it?

Yeah, that's why I asked before making such PR. I though this is not for everyone.
So I'd better go with 'favorite *pages*' in my navbar.

**Comment by talha131** [comment]
> So I'd better go with 'favorite pages' in my navbar.

Does this mean we can close this issue?

**Comment by azzamsa** [comment]
Yeah, I just wait your response :)

**Comment by azzamsa** [comment]
For anyone landing here:

I don't plan to add this feature to upstream pelican. This style is not for everyone.

But if you want, you can take [this commit](https://github.com/azzamsa/elegant/commit/e36229d570b99fc24c765d30b7aaea6543261af8) as patch and apply to your 'customized' theme.
