### ISSUE TITLE
[BUG] Elegant documentation website layout

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/elegant#543]
## Description

**Describe the bug**

I find this strange thing in our documentation website. is it okay?

**Screenshots**

Chromium:

![image](https://user-images.githubusercontent.com/17734314/70372599-cea1ba80-1913-11ea-8edc-de9120842359.png)

Firefox:

![image](https://user-images.githubusercontent.com/17734314/70372601-dbbea980-1913-11ea-922e-f64b0a316edc.png)

**Comment by talha131** [comment]
Which browser you are using? What's the screen size?

I cannot reproduce this issue at my end.

**Comment by azzamsa** [comment]
![image](https://user-images.githubusercontent.com/17734314/70382058-4f9a9980-1988-11ea-9b0e-3f5468ce89e0.png)

can you try using: http://testsize.com/

**Comment by talha131** [comment]
Cool site. Thanks for the hint.

Sorry, i could not reproduce it in testsize either.

![](https://i.imgur.com/Z5VodOj.png)

**Comment by talha131** [comment]
Cool site. Thanks for the hint.

Yeah, I can reproduce it. Will fix it.

**Comment by talha131** [comment]
## Information

1. This issue happens only on articles that have applause button enabled.
2. This line is the culprit https://github.com/Pelican-Elegant/elegant/blob/master/static/css/applause-button.css#L3

## Objective

Whatever be the solution, the applause button should be right-aligned.

## Notes

I am perplexed. Not sure what the reason is.

Perhaps we should use grid display to fix it. Perhaps the applause button CSS is messing up the layout.

**Comment by azzamsa** [comment]
But, It can't be reproduced using my blog: https://azzamsa.com/blog/kumpulan-panduan-emacs-berbahasa-indonesia. I've also try it using http://testsize.com/

**Comment by talha131** [comment]
Oh, I see. Thanks for the input.

I am not sure what the reason is.

>

**Comment by azzamsa** [comment]
Sorry, but I don't use pelican anymore.
Feel free to reopen the issue if needed. But I can't provide any further debug info.
