### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#74]
I haven't tested Elegant on any version of Internet Explorer. If you find any problem with Elegant on Internet Explorer, please feel free to submit a pull request.

**Comment by silverhook** [comment]
As IE is end-of-life, is this still relevant?

https://en.wikipedia.org/wiki/Internet_Explorer#End_of_life

**Comment by talha131** [comment]
Personally I think we shouldn't care much about supporting IE or older browser versions. This will let us use latest features like CSS-Grid which isn't supported on older browsers.

Supporting old browsers is too much work. I say we close this issue.

**Comment by silverhook** [comment]
I agree.

I would say the order should be:

1. W3C compliance as a must
1. Blink (Chromium) support
1. Gecko (Firefox) support
1. text-based browsers (Lynx, Elinks, W3) support
1. WebKit (Safari, Qt- and GTK-webkit, Opera, new Edge) support

Personally, I prefer Firefox to Chromium, but the market share is the other way around, so that make more sense.

**Comment by iranzo** [comment]
- w3c is tracked here: #251 
- text browsers in #224

**Comment by talha131** [comment]
IE is ancient history. Even MS has moved from it.

Considering the size of the team, we can't afford to have support for legacy browsers.

Also, we plan to use CSS grids and Flexbox in the theme which is not going to work on IE.
